### PR TITLE
Allow for redirection from generated routes

### PR DESCRIPTION
**Pull request by alexlafroscia**
If a route is defined in the router, but the file itself does not exist, register a "blank" route that can be reopened to add the redirection logic.  This helps keep the application cleaner and free of essentially empty route files.

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Not sure why the tests don't pass on `beta` but they pass in `default` and `release`

**Comment by thoov** [comment]
@alexlafroscia Thanks for this. The reason that the build is failing is that ember-beta and ember-data do not play well with each other and causes the modules below ED in the vendor.js file to not be accessible. Here is the related issue: https://github.com/emberjs/data/issues/3445

**Comment by thoov** [comment]
There are 2 ways in which you can fix the tests. One is to remove ember-data from package.json. And the other is to update [config/ember-try.js](https://raw.githubusercontent.com/thoov/ember-redirect/master/config/ember-try.js) and make sure that when testing on ember-beta we use ember-data-beta as well. I would like to see us do the latter. Let me know if you can add that to this PR or if you need my help.

**Comment by alexlafroscia** [comment]
Oh sure, I'd be happy to do that. I'll update the PR tonight.

**Comment by alexlafroscia** [comment]
I had to remove `ember-data` but I got it working. I tried keeping it, but that didn't seem to help.

**Pull request merged**
